version: "3"

services:
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9292"
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:14.5-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
